### ISSUE TITLE
First instance that fails on rinkeby

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-open-solver#45]
The following instance failed:
https://gist.github.com/josojo/ec760aa0a232251da044373d51136724

It was called with 
```
Apr 07 13:27:40.195 DEBG [driver::price_finding::price_finder_interface] Using open-solver command `"python" "-m" "src.match" "/app/instances/2020-04-07/instance_5287552_2020-04-07T13:27:40.155161734+00:00.json" "--solution=/app/results/2020-04-07/instance_5287552_2020-04-07T13:27:40.155161734+00:00/06_solution_int_valid.json" "best-token-pair"`
``` 

And the error message is:
```
Apr 07 13:27:41.624 ERRO [driver::price_finding::optimization_price_finder] Solver failed - stdout: , error: INFO   ::round   

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/open_solver/src/match.py", line 66, in <module>
    args.exec_subcommand(args)
  File "/app/open_solver/src/best_token_pair_solver/solver.py", line 98, in main
    token_pair, accounts, orders, fee
  File "/app/open_solver/src/best_token_pair_solver/solver.py", line 53, in match_token_pair_and_evaluate
    orders, prices = match_token_pair(token_pair, accounts, orders, fee)
  File "/app/open_solver/src/best_token_pair_solver/solver.py", line 46, in match_token_pair
    token_pair, accounts, b_orders, s_orders, f_orders, fee
  File "/app/open_solver/src/token_pair_solver/solver.py", line 338, in solve_token_pair_and_fee_token
    validate(accounts, orders, prices, fee)
  File "/app/open_solver/src/core/validation.py", line 53, in validate
    assert token_balances[token] == 0
AssertionError

```

**Comment by marcovc** [comment]
@josojo Can we close this one? I guess there will be plenty on the days to come :)

**Comment by josojo** [comment]
Yes, you had the fix for this one before it was reported. :) great
